language: java
jdk: openjdk7
env:
  global:
  - secure: 3f1ba4ef-6b1e-4ec6-a0fb-a21cedb7f024
deploy:
  provider: heroku
  api_key:
    secure: WJeYRe1APe2OAjsNR/5BiWNeRPpjpNEWXzUlCYJWiS7M5tkVKFpTB4xmyjYMlKM80fNEXhmankVXt8NZLrlkFioUWXyYeH6cjbK+qswDdcdKBS5GYbQE2MwdtudJC2iQQnEOUzUECCYIZWTRFNfnSGF1gJhTg2/FHEPT5ZwzS0w=
  app: pacific-castle-1001
  on:
    repo: DSTechSupport/tictactoe
